In [1]:
from __future__ import annotations
import sys
from pathlib import Path
import numpy as np
import pandas as pd
from pprint import pprint

hytraits_path = Path('../hytraits').resolve()
if str(hytraits_path) not in sys.path:
    sys.path.append(str(hytraits_path))
import hytraits as H
from utils import (get_trait_args,
                   get_paths,
                   get_traits,
                   get_train_config_json,
                   get_deploy_config_jsons,
                   get_eda_config_json)

In [2]:
PATHS = get_paths()

csv_file = PATHS['compatible']/'cfchl.csv'
dataset = H.CSVDataset(csv_file)
print(f'{len(dataset) = }')

data = dataset[None]
print(f'{data["x"].shape = }')
print(data['x'][:3, :3])
print(data['y_true'][:3])

len(dataset) = 150
data["x"].shape = (150, 412)
[[-0.01466429 -0.0132592  -0.01170431]
 [-0.01677496 -0.01528811 -0.0135326 ]
 [-0.01666988 -0.01496638 -0.01344397]]
[[5081.85]
 [5891.65]
 [7256.75]]


In [3]:
transform_json = PATHS['config']/'TRANSFORM__400-asis-raw.json'
transforms = H.load_transforms(transform_json)
data = dataset[None]
for transform in transforms:
    data = transform(data)
print(f'{data["x"].shape = }')
print(data['x'][:3, :3])
print(data['y_true'][:3])

data["x"].shape = (150, 124)
[[-0.11168242 -0.10098135 -0.08913937]
 [-0.13310778 -0.12130981 -0.10737999]
 [-0.16804243 -0.15087015 -0.13552331]]
[[5081.85]
 [5891.65]
 [7256.75]]


In [4]:
transform_json = PATHS['config']/'TRANSFORM__400-move-raw.json'
transforms = H.load_transforms(transform_json)
data = dataset[None]
for transform in transforms:
    data = transform(data)
print(f'{data["x"].shape = }')
print(data['x'][:3, :3])
print(data['y_true'][:3])

data["x"].shape = (150, 124)
[[3.57638490e-05 5.06089957e-03 1.06217932e-02]
 [3.43039332e-05 5.13476237e-03 1.11568545e-02]
 [3.74002001e-05 6.40851495e-03 1.21023684e-02]]
[[5081.85]
 [5891.65]
 [7256.75]]


In [5]:
transform_json = PATHS['config']/'TRANSFORM__400-move-pa-raw.json'
transforms = H.load_transforms(transform_json)
data = dataset[None]
for transform in transforms:
    data = transform(data)
print(f'{data["x"].shape = }')
print(data['x'][:3, :3])
print(data['y_true'][:3])

data["x"].shape = (150, 124)
[[0.26295754 0.14984459 0.1329117 ]
 [0.26521091 0.1498348  0.13195845]
 [0.26201459 0.14495258 0.13048345]]
[[5081.85]
 [5891.65]
 [7256.75]]


In [6]:
transform_json = PATHS['config']/'TRANSFORM__400-asis-log.json'
transforms = H.load_transforms(transform_json)
data = dataset[None]
for transform in transforms:
    data = transform(data)
print(f'{data["x"].shape = }')
print(data['x'][:3, :3])
print(data['y_true'][:3])

data["x"].shape = (150, 124)
[[-0.11168242 -0.10098135 -0.08913937]
 [-0.13310778 -0.12130981 -0.10737999]
 [-0.16804243 -0.15087015 -0.13552331]]
[[8.53343065]
 [8.68129137]
 [8.88968735]]


In [7]:
transform_json = PATHS['config']/'TRANSFORM__400-move-log.json'
transforms = H.load_transforms(transform_json)
data = dataset[None]
for transform in transforms:
    data = transform(data)
print(f'{data["x"].shape = }')
print(data['x'][:3, :3])
print(data['y_true'][:3])


data["x"].shape = (150, 124)
[[3.57638490e-05 5.06089957e-03 1.06217932e-02]
 [3.43039332e-05 5.13476237e-03 1.11568545e-02]
 [3.74002001e-05 6.40851495e-03 1.21023684e-02]]
[[8.53343065]
 [8.68129137]
 [8.88968735]]


In [8]:
transform_json = PATHS['config']/'TRANSFORM__400-move-pa-log.json'
transforms = H.load_transforms(transform_json)

data = dataset[None]
for transform in transforms:
    data = transform(data)
print(f'{data["x"].shape = }')
print(data['x'][:3, :3])
print(data['y_true'][:3])

data["x"].shape = (150, 124)
[[0.26295754 0.14984459 0.1329117 ]
 [0.26521091 0.1498348  0.13195845]
 [0.26201459 0.14495258 0.13048345]]
[[8.53343065]
 [8.68129137]
 [8.88968735]]


In [9]:
transform_json = PATHS['config']/'TRANSFORM__move-pa-log-eda.json'
transforms = H.load_transforms(transform_json)

data = dataset[None]
for transform in transforms:
    data = transform(data)

print(f'{data["x"].shape = }')
print(data['x'][:3, :3])
print(data['y_true'][:3])

data["x"].shape = (150, 124)
[[5.         2.84921653 2.52724641]
 [5.         2.82482357 2.48780215]
 [5.         2.76611652 2.49000356]]
[[8.53343065]
 [8.68129137]
 [8.88968735]]
